package com.huacheng.huiservers.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.huacheng.huiservers.model.ModelUser;

import com.huacheng.huiservers.greendao.ModelUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig modelUserDaoConfig;

    private final ModelUserDao modelUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        modelUserDaoConfig = daoConfigMap.get(ModelUserDao.class).clone();
        modelUserDaoConfig.initIdentityScope(type);

        modelUserDao = new ModelUserDao(modelUserDaoConfig, this);

        registerDao(ModelUser.class, modelUserDao);
    }
    
    public void clear() {
        modelUserDaoConfig.clearIdentityScope();
    }

    public ModelUserDao getModelUserDao() {
        return modelUserDao;
    }

}
